[project]
name = "jpx-tokyo-stock-exchange-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "itransformer>=0.8.1",
    "lightgbm>=4.6.0",
    "numpy>=2.4.2",
    "openai>=2.29.0",
    "pandas>=3.0.1",
    "scikit-learn>=1.8.0",
    "torch>=2.10.0",
    "tqdm>=4.67.3",
    "transformers>=5.2.0",
]
